export const SRI_LANKA_DISTRICTS = [
  'Ampara',
  'Anuradhapura',
  'Badulla',
  'Batticaloa',
  'Colombo',
  'Galle',
  'Gampaha',
  'Hambantota',
  'Jaffna',
  'Kalutara',
  'Kandy',
  'Kegalle',
  'Kilinochchi',
  'Kurunegala',
  'Mannar',
  'Matale',
  'Matara',
  'Monaragala',
  'Mullaitivu',
  'Nuwara Eliya',
  'Polonnaruwa',
  'Puttalam',
  'Ratnapura',
  'Trincomalee',
  'Vavuniya',
] as const;

export type SriLankaDistrict = typeof SRI_LANKA_DISTRICTS[number];

export const LAND_CRUISER_MODELS = [
  'Toyota Land Cruiser 300 Series (LC300)',
  'Toyota Land Cruiser 250 / Prado (2024+)',
  'Toyota Land Cruiser 200 Series (LC200)',
  'Toyota Land Cruiser 150 Series (Prado 150)',
  'Toyota Land Cruiser 120 Series (Prado 120)',
  'Toyota Land Cruiser 100 Series (LC100)',
  'Toyota Land Cruiser 90 Series (Prado 90)',
  'Toyota Land Cruiser 80 Series (LC80)',
  'Toyota Land Cruiser 70 Series (LC70 / LC76 / LC79)',
  'Toyota Land Cruiser 60 Series',
  'Toyota Land Cruiser 40 Series',
  'Toyota Land Cruiser FJ Cruiser',
  'Toyota Land Cruiser Cygnus',
  'Other / Custom Model',
] as const;
