export interface Country {
  code: string;
  dialCode: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: "LK", dialCode: "94", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "US", dialCode: "1", name: "United States", flag: "🇺🇸" },
  { code: "GB", dialCode: "44", name: "United Kingdom", flag: "🇬🇧" },
  { code: "IN", dialCode: "91", name: "India", flag: "🇮🇳" },
  { code: "AU", dialCode: "61", name: "Australia", flag: "🇦🇺" },
  { code: "CA", dialCode: "1", name: "Canada", flag: "🇨🇦" },
  { code: "AE", dialCode: "971", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "QA", dialCode: "974", name: "Qatar", flag: "🇶🇦" },
  { code: "SA", dialCode: "966", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "SG", dialCode: "65", name: "Singapore", flag: "🇸🇬" },
  { code: "MY", dialCode: "60", name: "Malaysia", flag: "🇲🇾" },
  { code: "NZ", dialCode: "64", name: "New Zealand", flag: "🇳🇿" },
  { code: "MV", dialCode: "960", name: "Maldives", flag: "🇲🇻" },
  { code: "OM", dialCode: "968", name: "Oman", flag: "🇴🇲" },
  { code: "KW", dialCode: "965", name: "Kuwait", flag: "🇰🇼" },
  { code: "BH", dialCode: "973", name: "Bahrain", flag: "🇧🇭" },
  { code: "DE", dialCode: "49", name: "Germany", flag: "🇩🇪" },
  { code: "FR", dialCode: "33", name: "France", flag: "🇫🇷" },
  { code: "IT", dialCode: "39", name: "Italy", flag: "🇮🇹" },
  { code: "JP", dialCode: "81", name: "Japan", flag: "🇯🇵" },
  { code: "CN", dialCode: "86", name: "China", flag: "🇨🇳" },
  { code: "CH", dialCode: "41", name: "Switzerland", flag: "🇨🇭" },
  { code: "NL", dialCode: "31", name: "Netherlands", flag: "🇳🇱" },
  { code: "SE", dialCode: "46", name: "Sweden", flag: "🇸🇪" },
  { code: "NO", dialCode: "47", name: "Norway", flag: "🇳🇴" },
  { code: "FI", dialCode: "358", name: "Finland", flag: "🇫🇮" },
  { code: "DK", dialCode: "45", name: "Denmark", flag: "🇩🇰" },
  { code: "HK", dialCode: "852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "KR", dialCode: "82", name: "South Korea", flag: "🇰🇷" },
  { code: "ZA", dialCode: "27", name: "South Africa", flag: "🇿🇦" },
  { code: "RU", dialCode: "7", name: "Russia", flag: "🇷🇺" },
  { code: "BR", dialCode: "55", name: "Brazil", flag: "🇧🇷" },
  { code: "MX", dialCode: "52", name: "Mexico", flag: "🇲🇽" },
  { code: "ES", dialCode: "34", name: "Spain", flag: "🇪🇸" },
  { code: "PT", dialCode: "351", name: "Portugal", flag: "🇵🇹" },
  { code: "TR", dialCode: "90", name: "Turkey", flag: "🇹🇷" },
  { code: "BD", dialCode: "880", name: "Bangladesh", flag: "🇧🇩" },
  { code: "PK", dialCode: "92", name: "Pakistan", flag: "🇵🇰" },
  { code: "NP", dialCode: "977", name: "Nepal", flag: "🇳🇵" },
  { code: "TH", dialCode: "66", name: "Thailand", flag: "🇹🇭" },
  { code: "ID", dialCode: "62", name: "Indonesia", flag: "🇮🇩" },
  { code: "PH", dialCode: "63", name: "Philippines", flag: "🇵🇭" },
  { code: "VN", dialCode: "84", name: "Vietnam", flag: "🇻🇳" },
  { code: "IE", dialCode: "353", name: "Ireland", flag: "🇮🇪" },
  { code: "AT", dialCode: "43", name: "Austria", flag: "🇦🇹" },
  { code: "BE", dialCode: "32", name: "Belgium", flag: "🇧🇪" },
  { code: "GR", dialCode: "30", name: "Greece", flag: "🇬🇷" },
].sort((a, b) => a.name.localeCompare(b.name));
